### ISSUE TITLE
Want a beta testeur ? Besoin d'un beta testeur

### ISSUE THREAD

**Issue by FeaReDGlock** [ungarscool1/FiveM-Inventory-Test#1]
Salut je vien ecrire ici car je sais pas comment t'envoyer des messages du coup je pesnes que tu es FR.
Donc je voudrais savoir si tu as besoin de quelqu'un pour test tes scripts sur un serveur ou il y en a deja pour voir qu'il y ai pas de probleme.

Si oui, dis moi et j'essaierais tes scripts 👍

**Comment by ungarscool1** [comment]
Salut, 
Je ne sais pas si je veux réellement faire un serveur gta5 rp. Si j'en ouvre un en effet j'aurais besoin de toi. 
Si tu veux tester le pôle emploi tu peux aller sur le serveur fivem "RP Ungarscool1 en dev" ou tu peux te connecter avec cette ip: ungarscool1.tk 

Si tu veux plus me parler voici mon steam: http://steamcommunity.com/id/Ungarscool1

**Comment by FeaReDGlock** [comment]
Apres tu choisis ce que tu veux faire, mais ouais, je savais pas si tu avais quelqu'un pour tester tes scripts car j'ai vu Need testing du coup, je me suis dis si tu as besoin n'hesite pas :)
